server:
  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    cache:
      clusterNodes: 127.0.0.1:6379,127.0.0.1:6380
      commandTimeout: 5000
mybatis:
  type-aliases-package: org.spring.springboot.vo
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql









